### ISSUE TITLE
No es posible desplegar en OpenShift

### ISSUE THREAD

**Issue by DanielRamosAcosta** [ULL-ESIT-SYTW-1617/practica-despliegues-en-iaas-y-heroku-rafadanipedro#1]
Nuestro servidor de Express tiene que clonar el gitbook, pero OpenShift no ofrece el servicio de crear directorios tal y como se explica en [este issue](https://github.com/rauchg/slackin/issues/155)... Una pena 😞

**Comment by Rafaherrero** [comment]
![](http://pix.iemoji.com/images/emoji/apple/ios-9/256/crying-face.png)
